from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..models.service_status import ServiceStatus
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.git import Git
    from ..models.helm_spec import HelmSpec
    from ..models.kustomize import Kustomize
    from ..models.service_error import ServiceError
    from ..models.service_renderer import ServiceRenderer
    from ..models.service_source import ServiceSource


T = TypeVar("T", bound="Service")


@_attrs_define
class Service:
    """A service deployment reference deployed from a git repo into a cluster

    Attributes:
        cluster_id (str | Unset): ID of the cluster this service is deployed to
        component_status (str | Unset): Status message from components (e.g. unhealthy reason)
        deleted_at (datetime.datetime | Unset): Timestamp the service was marked for deletion, if deleted
        dry_run (bool | Unset): If true, this service is running in dry-run mode
        errors (list[ServiceError] | Unset): List of errors generated by the deployment operator
        git (Git | Unset): Git reference configuration
        helm (HelmSpec | Unset): Helm chart configuration for a service
        id (str | Unset): Unique identifier for the service deployment
        inserted_at (datetime.datetime | Unset):
        interval (str | Unset): Polling interval for the service reconcile loop (e.g., "5m")
        kustomize (Kustomize | Unset): Kustomize configuration for a service
        message (str | Unset): Latest commit message from the synced revision
        name (str | Unset): Name of the service
        namespace (str | Unset): Kubernetes namespace where the service is deployed
        protect (bool | Unset): If true, prevents service deletion or config edits
        renderers (list[ServiceRenderer] | Unset): Custom renderers for processing service manifests
        repository_id (str | Unset): ID of the git or Helm repository backing this service
        sha (str | Unset): Git commit SHA for the current synced revision.  This will be a helm digest if a pure helm
            chart as well
        sources (list[ServiceSource] | Unset): Additional source repositories for this service
        status (ServiceStatus | Unset): Current status of the service deployment (e.g., stale, synced, healthy, failed,
            paused)
        templated (bool | Unset): If true, the service was deployed using a template
        updated_at (datetime.datetime | Unset):
    """

    cluster_id: str | Unset = UNSET
    component_status: str | Unset = UNSET
    deleted_at: datetime.datetime | Unset = UNSET
    dry_run: bool | Unset = UNSET
    errors: list[ServiceError] | Unset = UNSET
    git: Git | Unset = UNSET
    helm: HelmSpec | Unset = UNSET
    id: str | Unset = UNSET
    inserted_at: datetime.datetime | Unset = UNSET
    interval: str | Unset = UNSET
    kustomize: Kustomize | Unset = UNSET
    message: str | Unset = UNSET
    name: str | Unset = UNSET
    namespace: str | Unset = UNSET
    protect: bool | Unset = UNSET
    renderers: list[ServiceRenderer] | Unset = UNSET
    repository_id: str | Unset = UNSET
    sha: str | Unset = UNSET
    sources: list[ServiceSource] | Unset = UNSET
    status: ServiceStatus | Unset = UNSET
    templated: bool | Unset = UNSET
    updated_at: datetime.datetime | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        cluster_id = self.cluster_id

        component_status = self.component_status

        deleted_at: str | Unset = UNSET
        if not isinstance(self.deleted_at, Unset):
            deleted_at = self.deleted_at.isoformat()

        dry_run = self.dry_run

        errors: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.errors, Unset):
            errors = []
            for errors_item_data in self.errors:
                errors_item = errors_item_data.to_dict()
                errors.append(errors_item)

        git: dict[str, Any] | Unset = UNSET
        if not isinstance(self.git, Unset):
            git = self.git.to_dict()

        helm: dict[str, Any] | Unset = UNSET
        if not isinstance(self.helm, Unset):
            helm = self.helm.to_dict()

        id = self.id

        inserted_at: str | Unset = UNSET
        if not isinstance(self.inserted_at, Unset):
            inserted_at = self.inserted_at.isoformat()

        interval = self.interval

        kustomize: dict[str, Any] | Unset = UNSET
        if not isinstance(self.kustomize, Unset):
            kustomize = self.kustomize.to_dict()

        message = self.message

        name = self.name

        namespace = self.namespace

        protect = self.protect

        renderers: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.renderers, Unset):
            renderers = []
            for renderers_item_data in self.renderers:
                renderers_item = renderers_item_data.to_dict()
                renderers.append(renderers_item)

        repository_id = self.repository_id

        sha = self.sha

        sources: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.sources, Unset):
            sources = []
            for sources_item_data in self.sources:
                sources_item = sources_item_data.to_dict()
                sources.append(sources_item)

        status: str | Unset = UNSET
        if not isinstance(self.status, Unset):
            status = self.status.value

        templated = self.templated

        updated_at: str | Unset = UNSET
        if not isinstance(self.updated_at, Unset):
            updated_at = self.updated_at.isoformat()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if cluster_id is not UNSET:
            field_dict["cluster_id"] = cluster_id
        if component_status is not UNSET:
            field_dict["component_status"] = component_status
        if deleted_at is not UNSET:
            field_dict["deleted_at"] = deleted_at
        if dry_run is not UNSET:
            field_dict["dry_run"] = dry_run
        if errors is not UNSET:
            field_dict["errors"] = errors
        if git is not UNSET:
            field_dict["git"] = git
        if helm is not UNSET:
            field_dict["helm"] = helm
        if id is not UNSET:
            field_dict["id"] = id
        if inserted_at is not UNSET:
            field_dict["inserted_at"] = inserted_at
        if interval is not UNSET:
            field_dict["interval"] = interval
        if kustomize is not UNSET:
            field_dict["kustomize"] = kustomize
        if message is not UNSET:
            field_dict["message"] = message
        if name is not UNSET:
            field_dict["name"] = name
        if namespace is not UNSET:
            field_dict["namespace"] = namespace
        if protect is not UNSET:
            field_dict["protect"] = protect
        if renderers is not UNSET:
            field_dict["renderers"] = renderers
        if repository_id is not UNSET:
            field_dict["repository_id"] = repository_id
        if sha is not UNSET:
            field_dict["sha"] = sha
        if sources is not UNSET:
            field_dict["sources"] = sources
        if status is not UNSET:
            field_dict["status"] = status
        if templated is not UNSET:
            field_dict["templated"] = templated
        if updated_at is not UNSET:
            field_dict["updated_at"] = updated_at

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        from ..models.git import Git
        from ..models.helm_spec import HelmSpec
        from ..models.kustomize import Kustomize
        from ..models.service_error import ServiceError
        from ..models.service_renderer import ServiceRenderer
        from ..models.service_source import ServiceSource

        d = dict(src_dict)
        cluster_id = d.pop("cluster_id", UNSET)

        component_status = d.pop("component_status", UNSET)

        _deleted_at = d.pop("deleted_at", UNSET)
        deleted_at: datetime.datetime | Unset
        if isinstance(_deleted_at, Unset):
            deleted_at = UNSET
        else:
            deleted_at = datetime.datetime.fromisoformat(_deleted_at)

        dry_run = d.pop("dry_run", UNSET)

        _errors = d.pop("errors", UNSET)
        errors: list[ServiceError] | Unset = UNSET
        if _errors is not UNSET:
            errors = []
            for errors_item_data in _errors:
                errors_item = ServiceError.from_dict(errors_item_data)

                errors.append(errors_item)

        _git = d.pop("git", UNSET)
        git: Git | Unset
        if isinstance(_git, Unset):
            git = UNSET
        else:
            git = Git.from_dict(_git)

        _helm = d.pop("helm", UNSET)
        helm: HelmSpec | Unset
        if isinstance(_helm, Unset):
            helm = UNSET
        else:
            helm = HelmSpec.from_dict(_helm)

        id = d.pop("id", UNSET)

        _inserted_at = d.pop("inserted_at", UNSET)
        inserted_at: datetime.datetime | Unset
        if isinstance(_inserted_at, Unset):
            inserted_at = UNSET
        else:
            inserted_at = datetime.datetime.fromisoformat(_inserted_at)

        interval = d.pop("interval", UNSET)

        _kustomize = d.pop("kustomize", UNSET)
        kustomize: Kustomize | Unset
        if isinstance(_kustomize, Unset):
            kustomize = UNSET
        else:
            kustomize = Kustomize.from_dict(_kustomize)

        message = d.pop("message", UNSET)

        name = d.pop("name", UNSET)

        namespace = d.pop("namespace", UNSET)

        protect = d.pop("protect", UNSET)

        _renderers = d.pop("renderers", UNSET)
        renderers: list[ServiceRenderer] | Unset = UNSET
        if _renderers is not UNSET:
            renderers = []
            for renderers_item_data in _renderers:
                renderers_item = ServiceRenderer.from_dict(renderers_item_data)

                renderers.append(renderers_item)

        repository_id = d.pop("repository_id", UNSET)

        sha = d.pop("sha", UNSET)

        _sources = d.pop("sources", UNSET)
        sources: list[ServiceSource] | Unset = UNSET
        if _sources is not UNSET:
            sources = []
            for sources_item_data in _sources:
                sources_item = ServiceSource.from_dict(sources_item_data)

                sources.append(sources_item)

        _status = d.pop("status", UNSET)
        status: ServiceStatus | Unset
        if isinstance(_status, Unset):
            status = UNSET
        else:
            status = ServiceStatus(_status)

        templated = d.pop("templated", UNSET)

        _updated_at = d.pop("updated_at", UNSET)
        updated_at: datetime.datetime | Unset
        if isinstance(_updated_at, Unset):
            updated_at = UNSET
        else:
            updated_at = datetime.datetime.fromisoformat(_updated_at)

        service = cls(
            cluster_id=cluster_id,
            component_status=component_status,
            deleted_at=deleted_at,
            dry_run=dry_run,
            errors=errors,
            git=git,
            helm=helm,
            id=id,
            inserted_at=inserted_at,
            interval=interval,
            kustomize=kustomize,
            message=message,
            name=name,
            namespace=namespace,
            protect=protect,
            renderers=renderers,
            repository_id=repository_id,
            sha=sha,
            sources=sources,
            status=status,
            templated=templated,
            updated_at=updated_at,
        )

        service.additional_properties = d
        return service

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
